config/routes.rb
Rails.application.routes.draw do
  resources :reserved_lockers

  get 'welcome/index'
  root "welcome#index"

end

app/models/reserved_locker.rb
class ReservedLocker < ActiveRecord::Base
  validates :size, inclusion: { in: %w(Small Regular Large),
                                message: "%{value} is not a valid size" }
  validates :number, numericality: true
  validates :size, :number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reserved_lockers_controller.rb
class ReservedLockersController < ApplicationController
  # def new
  #   render plain: params[:reserved_locker].inspect
  # end

  def create
    params = reserved_locker_params

    # Locker reservations are segregated 1-1000 small, 1001-2000 regular, 2001-3000 large
    # start looking for gaps
    prev = -1 + start =  1 if (params[:size] == 'Small')
    prev = -1 + start = 1001 if (params[:size] == 'Regular')
    prev = -1 + start = 2001 if (params[:size] == 'Large')
    found = false
    lockers = ReservedLocker.where(size: params[:size]).order(:number)
    lockers.find_each { |locker|
      unless (((locker.number - 1) == prev) || (locker.number == start))
        found = true
        params[:number] = locker.number - 1
        break
      end
      prev = locker.number
    }

    # couldn't find a valid low number or gap
    unless found
      # it could be that no reservations were found if so just pick the lowest possible (which is next)
      if (lockers.any?)
        params[:number] = prev + 1
      else
        # Just starting
        params[:number] = start
      end
    end

    @reserved_locker = ReservedLocker.new(params)
    # Only save if we haven't run out of lockers (3000) and if we did save perform a redirection...this happens
    # because of the left evaluating first and the && short circuiting on failure
    if ((params[:number].nil? || (!(params[:number] > 3000))) &&  @reserved_locker.save)
      redirect_to @reserved_locker
    else
      redirect_to action: 'create'
    end
  end

  def show
    @reserved_locker = ReservedLocker.find(params[:id])
  end

  def index
    @reserved_lockers = ReservedLocker.all
  end

  def destroy
    # NOTE BENE: We delete by locker number and not by ID
    @reserved_locker = ReservedLocker.find(params[:id])
    @reserved_locker.delete
    redirect_to action: 'index'
  end

  private
  def reserved_locker_params
    params.require(:reserved_locker).permit(:id, :size, :number)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locker_manager_helper.rb
module LockerManagerHelper
end

app/helpers/reserved_lockers_helper.rb
module ReservedLockersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Locker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/reserved_lockers/_menu.html.haml
%p
%a{:href => "/reserved_lockers"} Show Lockers
%a{:href => "/reserved_lockers/new"} Reserve Locker

app/views/reserved_lockers/create.html.haml
%strong Checkout

= form_for :reserved_locker, url: reserved_lockers_path do |f|
  %p
    Select a locker size:
    = f.select :size, :options => ['Small', 'Regular', 'Large'], :selected => 'Small'
  %p
    = f.submit 'Reserve'

.menu
  = render 'reserved_lockers/menu'

app/views/reserved_lockers/index.html.haml
- @reserved_lockers.each do |locker|
  %p
    = locker.number
    = locker.size

    = link_to 'Release Locker', reserved_locker_path(locker), method: :delete, data: { confirm: 'Are you sure?' }

.menu
  = render 'reserved_lockers/menu'

app/views/reserved_lockers/new.html.haml
%strong Checkout

= form_for :reserved_locker, url: reserved_lockers_path do |f|
  %p
    Select a locker size:
    = f.select :size, :options => ['Small', 'Regular', 'Large'], :selected => 'Small'
  %p
    = f.submit 'Reserve'

.menu
  = render 'reserved_lockers/menu'

app/views/reserved_lockers/show.html.haml
:javascript
  function printDiv(divName) {
   alert(divName);
   var printContents = document.getElementById(divName).innerHTML;
   w=window.open();
   w.document.write(printContents);
   w.print();
   w.close();
  }

#print_content
  %strong
    Reservation For
    = @reserved_locker.number
  Locker
  %strong
    = @reserved_locker.size

%p
%input{:type=>'button', :onclick=>"printDiv('print_content')", :value=>'Print Reservation'}

.menu
  = render 'reserved_lockers/menu'

app/views/welcome/index.html.haml
%h1 Sprawling Hotels

%p Locker reservation system

.menu
  = render 'reserved_lockers/menu'